name: "check properties"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup environment
      run: nix develop --command make verilog-wrappers verilog-props
    - name: Run property checks
      run: nix develop --command make check-prop
